export const INDEXABLE_STATIC_PATHS = [
  '/es/',
  '/es/unas-semicuradas/',
  '/es/mejores-unas-semicuradas/',
  '/es/que-son-las-unas-semicuradas/',
  '/es/como-poner-unas-semicuradas/',
  '/es/unas-semicuradas-francesas/',
  '/es/unas-semicuradas-con-lampara/',
  '/es/como-quitar-unas-semicuradas/',
  '/es/tornos-unas/',
  '/es/aspiradores-polvo-unas/',
  '/es/impresoras-unas-3d/',
  '/es/impresoras-unas-3d/como-funcionan/',
  '/es/impresoras-unas-3d/precio/',
  '/es/impresoras-unas-3d/profesionales/',
  '/es/impresoras-unas-3d/4800-vs-12000-dpi/',
  '/es/impresoras-unas-3d/cartuchos-y-consumibles/',
  '/es/comparar/',
  '/es/calculadora-ahorro-manicura/',
  '/es/calculadora-rentabilidad-impresora-unas/',
  '/es/encuentra-tus-unas/',
  '/es/sobre-nosotras/',
  '/es/metodologia/',
  '/es/aviso-afiliados/',
] as const;
